#CMD: docker-compose -f compose.yaml -p nanowolf up --build

services:
  postgres:
    build: ./postgres  
    container_name: cryptofacil-postgres
    environment:
      POSTGRES_USER: admin0109
      POSTGRES_PASSWORD: marAberto2256!@#
      POSTGRES_DB: dbcryptofacil
      POSTGRES_INITDB_ARGS: "--locale=pt_BR.UTF-8 --encoding=UTF8"
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
    networks:
      - cryptofacil-network

volumes: 
  postgres_data:
    driver: local

networks:
  cryptofacil-network:
    driver: bridge